#!/usr/bin/python
# -*- coding: UTF-8 -*-

import pymysql

def user():
	userDict = {}
	conn = pymysql.connect(host='127.0.0.1', port=3306, user='root', passwd='root', db='risk-cms', charset='utf8')
	cursor = conn.cursor()
	aa = cursor.execute("select * from cbc_credit_result_user ");
	info = cursor.fetchmany(aa)
	for ii in info:
		userDict[ii[1]] = ii[2]+","+ii[3]+","+ii[4]+","+ii[5]+","+ii[10]
	return userDict

def first(userDict):
	result = ()
	conn = pymysql.connect(host='127.0.0.1', port=3306, user='root', passwd='root', db='risk-cms', charset='utf8')
	cursor = conn.cursor()
	aa = cursor.execute("select uid,rulescore,decisionResult from tb_deal_receive_data where id <= 705");
	info = cursor.fetchmany(aa)
	file_object = open("d:/project/python/1.txt","w")
	for ii in info:
		if ii[2] == '1':
			file_object.writelines(ii[0]+","+userDict[ii[0]]+","+"1,1,1\n")
		else:
			if int(ii[1].find('r1=1')) >= 0:
				if int(ii[1].find('r2=1')) >= 0:
					if int(ii[1].find('r3=1')) >= 0:
						if int(ii[1].find('r4=1')) >= 0:
							file_object.writelines(ii[0]+","+userDict[ii[0]]+","+"1,1,1\n")
						else:
							file_object.writelines(ii[0]+","+userDict[ii[0]]+","+"0,0,1\n")
					else:
						file_object.writelines(ii[0]+","+userDict[ii[0]]+","+"0,1,1\n")
				else:
					file_object.writelines(ii[0]+","+userDict[ii[0]]+","+"0,1,1\n")
			else:
				file_object.writelines(ii[0]+","+userDict[ii[0]]+","+"1,1,1\n")

	file_object.close()

def bairongandyouli(userDict):
	result = ()
	conn = pymysql.connect(host='127.0.0.1', port=3306, user='root', passwd='root', db='risk-cms', charset='utf8')
	cursor = conn.cursor()
	aa = cursor.execute("select uid,rulescore,decisionResult from tb_deal_receive_data where id <= 10023 and id > 705");
	info = cursor.fetchmany(aa)
	file_object = open("d:/project/python/2.txt","w")
	for ii in info:
		if ii[2] == '1':
			file_object.writelines(ii[0]+","+userDict[ii[0]]+","+"1,1,1\n")
		else:
			if int(ii[1].find('r2=0')) > 1 or int(ii[1].find('r3=0')) > 1 or int(ii[1].find('r4=0')) > 1:
				file_object.writelines(ii[0]+","+bb+","+"0,1,1\n")
			elif int(ii[1].find('r5=0')) > 1:
				file_object.writelines(ii[0]+","+bb+","+"1,0,1\n")
			else:
				file_object.writelines(ii[0]+","+bb+","+"1,1,1\n")

	file_object.close()

def bairong(userDict):
	result = ()
	conn = pymysql.connect(host='127.0.0.1', port=3306, user='root', passwd='root', db='risk-cms', charset='utf8')
	cursor = conn.cursor()
	aa = cursor.execute("select uid,rulescore,decisionResult from tb_deal_receive_data where id <= 158441 and id > 10023");
	info = cursor.fetchmany(aa)
	file_object = open("d:/project/python/3.txt","w")
	i = 0
	for ii in info:
		bb = userDict.get(ii[0],"1")
		if bb != '1':
			if ii[2] == '1':
				file_object.writelines(ii[0]+","+bb+","+"1,1,1\n")
			else:
				if int(ii[1].find('r2=0')) > 1 or int(ii[1].find('r3=0')) > 1 or int(ii[1].find('r4=0')) > 1:
					file_object.writelines(ii[0]+","+bb+","+"0,1,1\n")
				else:
					file_object.writelines(ii[0]+","+bb+","+"1,1,1\n")
		else:
			i = i + 1
			print(i)

	file_object.close()

def bairongandqianhai(userDict):
	result = ()
	conn = pymysql.connect(host='127.0.0.1', port=3306, user='root', passwd='root', db='risk-cms', charset='utf8')
	cursor = conn.cursor()
	aa = cursor.execute("select uid,rulescore,decisionResult from tb_deal_receive_data where id > 158441");
	info = cursor.fetchmany(aa)
	file_object = open("d:/project/python/4.txt","w")
	i = 0
	for ii in info:
		bb = userDict.get(ii[0],"1")
		if bb != '1':
			if ii[2] == '1':
				file_object.writelines(ii[0]+","+bb+","+"1,1,1\n")
			else:
				if int(ii[1].find('r2=0')) > 1 or int(ii[1].find('r3=0')) > 1 or int(ii[1].find('r4=0')) > 1:
					file_object.writelines(ii[0]+","+bb+","+"0,1,1\n")
				else:
					file_object.writelines(ii[0]+","+bb+","+"1,1,1\n")
		else:
			i = i + 1
			print(i)

	file_object.close()



userDict=user()
#first(userDict)
#bairongandyouli(userDict)
bairong(userDict)

